name: 'Deploy to environment'
description: 'Deploys python-greetings using pm2'

inputs:
  environment:
    description: 'Target environment'
    required: true
  port:
    description: 'Port number'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout pipeline repo
      uses: actions/checkout@v4

    - name: Clone python-greetings repository
      uses: actions/checkout@v4
      with:
        repository: mtararujs/python-greetings
        path: python-greetings

    - name: Create virtual environment
      shell: powershell
      run: |
        $appPath = "$env:GITHUB_WORKSPACE\python-greetings"
        Set-Location $appPath
        python -m venv venv

    - name: Install pip dependencies
      shell: powershell
      run: |
        $appPath = "$env:GITHUB_WORKSPACE\python-greetings"
        & "$appPath\venv\Scripts\python.exe" -m pip install -r "$appPath\requirements.txt"

    - name: Stop existing service if running
      shell: cmd
      run: pm2 delete greetings-app-${{ inputs.environment }} & EXIT /B 0

    - name: Start service with pm2
      shell: powershell
      run: |
        $appPath = "$env:GITHUB_WORKSPACE\python-greetings"
        pm2 start "$appPath\app.py" --name "greetings-app-${{ inputs.environment }}" --interpreter "$appPath\venv\Scripts\python.exe" -- --port ${{ inputs.port }}